# Importing the Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the datasets

In [2]:
dataset=pd.read_csv("new_retail_data (1).csv",parse_dates=['Date'])
dataset

Transaction_ID  Customer_ID                 Name  \
0            8691788.0      37249.0  Michelle Harrington   
1            2174773.0      69749.0          Kelsey Hill   
2            6679610.0      30192.0         Scott Jensen   
3            7232460.0      62101.0        Joseph Miller   
4            4983775.0      27901.0        Debra Coleman   
...                ...          ...                  ...   
302005       4246475.0      12104.0         Meagan Ellis   
302006       1197603.0      69772.0          Mathew Beck   
302007       7743242.0      28449.0           Daniel Lee   
302008       9301950.0      45477.0       Patrick Wilson   
302009       2882826.0      53626.0       Dustin Merritt   

                           Email         Phone                       Address  \
0              Ebony39@gmail.com  1.414787e+09             3959 Amanda Burgs   
1               Mark36@gmail.com  6.852900e+09            82072 Dawn Centers   
2              Shane85@gmail.com  8.362160e+09             4133 Young Canyon   
3               Mary34@gmail.com  2.776752e+09   8148 Thomas Creek Suite 100   
4            Charles30@gmail.com  9.098268e+09     5813 Lori Ports Suite 269   
...                          ...           ...                           ...   
302005      Courtney60@gmail.com  7.466354e+09        389 Todd Path Apt. 159   
302006      Jennifer71@gmail.com  5.754305e+09             52809 Mark Forges   
302007  Christopher100@gmail.com  9.382530e+09  407 Aaron Crossing Suite 495   
302008       Rebecca65@gmail.com  9.373222e+09               3204 Baird Port   
302009       William14@gmail.com  9.518927e+09           143 Amanda Crescent   

              City            State  Zipcode    Country  ...  Total_Amount  \
0         Dortmund           Berlin  77985.0    Germany  ...    324.086270   
1       Nottingham          England  99071.0         UK  ...    806.707815   
2          Geelong  New South Wales  75929.0  Australia  ...   1063.432799   
3         Edmonton          Ontario  88420.0     Canada  ...   2466.854021   
4          Bristol          England  48704.0         UK  ...    248.553049   
...            ...              ...      ...        ...  ...           ...   
302005  Townsville  New South Wales   4567.0  Australia  ...    973.962984   
302006     Hanover           Berlin  16852.0    Germany  ...    285.137301   
302007    Brighton          England  88038.0         UK  ...    182.105285   
302008     Halifax          Ontario  67608.0     Canada  ...    120.834784   
302009      Tucson    West Virginia  25242.0        USA  ...   2382.233417   

       Product_Category  Product_Brand Product_Type   Feedback  \
0              Clothing           Nike       Shorts  Excellent   
1           Electronics        Samsung       Tablet  Excellent   
2                 Books  Penguin Books   Children's    Average   
3            Home Decor     Home Depot        Tools  Excellent   
4               Grocery         Nestle    Chocolate        Bad   
...                 ...            ...          ...        ...   
302005            Books  Penguin Books      Fiction        Bad   
302006      Electronics          Apple       Laptop  Excellent   
302007         Clothing         Adidas       Jacket    Average   
302008       Home Decor           IKEA    Furniture       Good   
302009       Home Decor     Home Depot  Decorations    Average   

        Shipping_Method Payment_Method Order_Status  Ratings  \
0              Same-Day     Debit Card      Shipped      5.0   
1              Standard    Credit Card   Processing      4.0   
2              Same-Day    Credit Card   Processing      2.0   
3              Standard         PayPal   Processing      4.0   
4              Standard           Cash      Shipped      1.0   
...                 ...            ...          ...      ...   
302005         Same-Day           Cash   Processing      1.0   
302006         Same-Day           Cash   Processing      5.0   
302007          Expr

# Some Extra Functions

In [3]:
dataset.shape

(302010, 30)

In [4]:
dataset.isnull().sum()

Transaction_ID      333
Customer_ID         308
Name                382
Email               347
Phone               362
Address             315
City                248
State               281
Zipcode             340
Country             271
Age                 173
Gender              317
Income              290
Customer_Segment    215
Date                359
Year                350
Month               273
Time                350
Total_Purchases     361
Amount              357
Total_Amount        350
Product_Category    283
Product_Brand       281
Product_Type          0
Feedback            184
Shipping_Method     337
Payment_Method      297
Order_Status        235
Ratings             184
products              0
dtype: int64

In [5]:
dropped_values=dataset.dropna()

In [6]:
dropped_values.count()

Transaction_ID      293911
Customer_ID         293911
Name                293911
Email               293911
Phone               293911
Address             293911
City                293911
State               293911
Zipcode             293911
Country             293911
Age                 293911
Gender              293911
Income              293911
Customer_Segment    293911
Date                293911
Year                293911
Month               293911
Time                293911
Total_Purchases     293911
Amount              293911
Total_Amount        293911
Product_Category    293911
Product_Brand       293911
Product_Type        293911
Feedback            293911
Shipping_Method     293911
Payment_Method      293911
Order_Status        293911
Ratings             293911
products            293911
dtype: int64

In [7]:
dropped_values.isnull().sum()

Transaction_ID      0
Customer_ID         0
Name                0
Email               0
Phone               0
Address             0
City                0
State               0
Zipcode             0
Country             0
Age                 0
Gender              0
Income              0
Customer_Segment    0
Date                0
Year                0
Month               0
Time                0
Total_Purchases     0
Amount              0
Total_Amount        0
Product_Category    0
Product_Brand       0
Product_Type        0
Feedback            0
Shipping_Method     0
Payment_Method      0
Order_Status        0
Ratings             0
products            0
dtype: int64

In [8]:
dataset.fillna(0)

Transaction_ID  Customer_ID                 Name  \
0            8691788.0      37249.0  Michelle Harrington   
1            2174773.0      69749.0          Kelsey Hill   
2            6679610.0      30192.0         Scott Jensen   
3            7232460.0      62101.0        Joseph Miller   
4            4983775.0      27901.0        Debra Coleman   
...                ...          ...                  ...   
302005       4246475.0      12104.0         Meagan Ellis   
302006       1197603.0      69772.0          Mathew Beck   
302007       7743242.0      28449.0           Daniel Lee   
302008       9301950.0      45477.0       Patrick Wilson   
302009       2882826.0      53626.0       Dustin Merritt   

                           Email         Phone                       Address  \
0              Ebony39@gmail.com  1.414787e+09             3959 Amanda Burgs   
1               Mark36@gmail.com  6.852900e+09            82072 Dawn Centers   
2              Shane85@gmail.com  8.362160e+09             4133 Young Canyon   
3               Mary34@gmail.com  2.776752e+09   8148 Thomas Creek Suite 100   
4            Charles30@gmail.com  9.098268e+09     5813 Lori Ports Suite 269   
...                          ...           ...                           ...   
302005      Courtney60@gmail.com  7.466354e+09        389 Todd Path Apt. 159   
302006      Jennifer71@gmail.com  5.754305e+09             52809 Mark Forges   
302007  Christopher100@gmail.com  9.382530e+09  407 Aaron Crossing Suite 495   
302008       Rebecca65@gmail.com  9.373222e+09               3204 Baird Port   
302009       William14@gmail.com  9.518927e+09           143 Amanda Crescent   

              City            State  Zipcode    Country  ...  Total_Amount  \
0         Dortmund           Berlin  77985.0    Germany  ...    324.086270   
1       Nottingham          England  99071.0         UK  ...    806.707815   
2          Geelong  New South Wales  75929.0  Australia  ...   1063.432799   
3         Edmonton          Ontario  88420.0     Canada  ...   2466.854021   
4          Bristol          England  48704.0         UK  ...    248.553049   
...            ...              ...      ...        ...  ...           ...   
302005  Townsville  New South Wales   4567.0  Australia  ...    973.962984   
302006     Hanover           Berlin  16852.0    Germany  ...    285.137301   
302007    Brighton          England  88038.0         UK  ...    182.105285   
302008     Halifax          Ontario  67608.0     Canada  ...    120.834784   
302009      Tucson    West Virginia  25242.0        USA  ...   2382.233417   

       Product_Category  Product_Brand Product_Type   Feedback  \
0              Clothing           Nike       Shorts  Excellent   
1           Electronics        Samsung       Tablet  Excellent   
2                 Books  Penguin Books   Children's    Average   
3            Home Decor     Home Depot        Tools  Excellent   
4               Grocery         Nestle    Chocolate        Bad   
...                 ...            ...          ...        ...   
302005            Books  Penguin Books      Fiction        Bad   
302006      Electronics          Apple       Laptop  Excellent   
302007         Clothing         Adidas       Jacket    Average   
302008       Home Decor           IKEA    Furniture       Good   
302009       Home Decor     Home Depot  Decorations    Average   

        Shipping_Method Payment_Method Order_Status  Ratings  \
0              Same-Day     Debit Card      Shipped      5.0   
1              Standard    Credit Card   Processing      4.0   
2              Same-Day    Credit Card   Processing      2.0   
3              Standard         PayPal   Processing      4.0   
4              Standard           Cash      Shipped      1.0   
...                 ...            ...          ...      ...   
302005         Same-Day           Cash   Processing      1.0   
302006         Same-Day           Cash   Processing      5.0   
302007          Expr

# Seperating dependent and independent variables

In [9]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [10]:
x

array([[8691788.0, 37249.0, 'Michelle Harrington', ..., 'Debit Card',
        'Shipped', 5.0],
       [2174773.0, 69749.0, 'Kelsey Hill', ..., 'Credit Card',
        'Processing', 4.0],
       [6679610.0, 30192.0, 'Scott Jensen', ..., 'Credit Card',
        'Processing', 2.0],
       ...,
       [7743242.0, 28449.0, 'Daniel Lee', ..., 'Cash', 'Shipped', 2.0],
       [9301950.0, 45477.0, 'Patrick Wilson', ..., 'Cash', 'Shipped',
        4.0],
       [2882826.0, 53626.0, 'Dustin Merritt', ..., 'Cash', 'Shipped',
        2.0]], dtype=object)

In [11]:
y

array(['Cycling shorts', 'Lenovo Tab', 'Sports equipment', ..., 'Parka',
       'TV stand', 'Clocks'], dtype=object)

# Seperating each column

In [12]:
ag=dataset.iloc[:,0].values
u=dataset.iloc[:,1].values
a=dataset.iloc[:,2].values
b=dataset.iloc[:,3].values
v=dataset.iloc[:,4].values
c=dataset.iloc[:,5].values
d=dataset.iloc[:,6].values
e=dataset.iloc[:,7].values
w=dataset.iloc[:,8].values
f=dataset.iloc[:,9].values
z=dataset.iloc[:,10].values
g=dataset.iloc[:,11].values
h=dataset.iloc[:,12].values
i=dataset.iloc[:,13].values
j=dataset.iloc[:,14].values
ab=dataset.iloc[:,15].values
k=dataset.iloc[:,16].values
l=dataset.iloc[:,17].values
ac=dataset.iloc[:,18].values
ad=dataset.iloc[:,19].values
ae=dataset.iloc[:,20].values
m=dataset.iloc[:,21].values
n=dataset.iloc[:,22].values
o=dataset.iloc[:,23].values
p=dataset.iloc[:,24].values
q=dataset.iloc[:,25].values
r=dataset.iloc[:,26].values
s=dataset.iloc[:,27].values
af=dataset.iloc[:,28].values

In [14]:
print(a)

['Michelle Harrington' 'Kelsey Hill' 'Scott Jensen' ... 'Daniel Lee'
 'Patrick Wilson' 'Dustin Merritt']


# Encoding each variable

In [15]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
ag=le.fit_transform(ag)
u=le.fit_transform(u)
a=le.fit_transform(a)
b=le.fit_transform(b)
v=le.fit_transform(v)
c=le.fit_transform(c)
d=le.fit_transform(d)
e=le.fit_transform(e)
w=le.fit_transform(w)
f=le.fit_transform(f)
z=le.fit_transform(z)
g=le.fit_transform(g)
h=le.fit_transform(h)
i=le.fit_transform(i)
j=le.fit_transform(j)
ab=le.fit_transform(ab)
k=le.fit_transform(k)
l=le.fit_transform(l)
ac=le.fit_transform(ac)
ad=le.fit_transform(ad)
ae=le.fit_transform(ae)
m=le.fit_transform(m)
n=le.fit_transform(n)
o=le.fit_transform(o)
p=le.fit_transform(p)
q=le.fit_transform(q)
r=le.fit_transform(r)
s=le.fit_transform(s)
af=le.fit_transform(af)


In [16]:
print(a)

[109110  86175 135685 ...  37087 121115  47724]


# Combining these encoded columns

In [17]:
x=np.array([ag,u,a,b,v,c,d,e,w,f,z,g,h,i,j,ab,k,l,ac,ad,ae,m,n,o,p,q,r,s,af])
X=x.transpose()
X

array([[251938,  26267, 109110, ...,      2,      3,      4],
       [ 38363,  57607,  86175, ...,      1,      2,      3],
       [186304,  19456, 135685, ...,      1,      2,      1],
       ...,
       [221012,  17779,  37087, ...,      0,      3,      1],
       [271731,  34222, 121115, ...,      0,      3,      3],
       [ 61541,  42041,  47724, ...,      0,      3,      1]], dtype=int64)

In [18]:
X.shape

(302010, 29)

# Splitting the dataset into the training and test set

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)
print(X_train)

[[186994  13414  15404 ...      2      3      1]
 [ 91698  73339 141117 ...      1      1      0]
 [145978  27851  38348 ...      1      0      0]
 ...
 [110543  63573  33039 ...      1      3      0]
 [257677  59309 115082 ...      0      0      3]
 [243068  15891  29326 ...      2      0      2]]


In [20]:
print(X_test)

[[ 91854  75448  81621 ...      0      0      2]
 [188788  68730 129049 ...      2      2      3]
 [ 98019  11181  74473 ...      0      0      3]
 ...
 [216016  46693  52216 ...      2      1      1]
 [171218   4975 109628 ...      1      3      0]
 [137727  37810 106391 ...      1      0      0]]


In [21]:
print(y_train)

[ 63 272  38 ...  82  48  88]


In [22]:
print(y_test)

[ 62 105 260 ... 237  58 237]


# Predicting the rating based on Amount and Total amount spent using Simple Linear Regression 

In [23]:
aj=dataset.iloc[:,19]
ah=dataset.iloc[:,20]
ai=dataset.iloc[:,28]

In [24]:
aj=le.fit_transform(aj)
ah=le.fit_transform(ah)
ai=le.fit_transform(ai)

In [25]:
ak=np.array([aj,ah])
AK=ak.transpose()
AI=ai.transpose()
from sklearn.model_selection import train_test_split
AK_train,AK_test,AI_train,AI_test=train_test_split(AK,AI,test_size=0.2,random_state=0)
AK_train

array([[ 19691,  25109],
       [165822,  45717],
       [231913, 270123],
       ...,
       [ 13982,  24087],
       [278375, 259146],
       [175226, 226970]], dtype=int64)

In [26]:
AK_test

array([[153015, 211519],
       [194670, 105065],
       [273715,  78483],
       ...,
       [206985, 180535],
       [103903,  91190],
       [116718, 164377]], dtype=int64)

In [27]:
AI_train

array([0, 2, 3, ..., 3, 1, 3], dtype=int64)

In [28]:
AI_test

array([2, 3, 2, ..., 0, 3, 2], dtype=int64)

In [29]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(AK_train,AI_train)

LinearRegression()

In [30]:
y_pred=regressor.predict(AK_test)
y_pred

array([2.16008057, 2.1731959 , 2.18053654, ..., 2.16637636, 2.16920773,
       2.16264616])